---
provider: openstack
cloud_service_group: Compute
cloud_service_type: Image
name: Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            operator: count
options:
  value_options:
    key: value
    options:
      default: 0